alias pg_start="postgres -D /usr/local/var/postgres"
alias pg_stop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
alias mongo_start="mongod run --config /usr/local/etc/mongod.conf"
alias mysql_start="nohup mysql.server start"
alias mysql_stop="mysql.server stop"
alias redis_start="redis-server /usr/local/etc/redis.conf"
alias redis="redis-cli"
